version: '3'
services:
  web:
    build:
      context: .
      args:
        - RAILS_ENV=test
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - "3000-3005:3000"
    environment:
      RAILS_ENV: test
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_MAX_THREADS: 5
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - '.:/rails_booking_system'

volumes:
  redis: